Improve Develocity build scan support
apache/logging-parent pull request #207
Opened 2024-07-17 14:16 UTC by jprinet

In order to improve the [Develocity](https://ge.apache.org/) Build Scan support on the Log4j2 project, this PR provides:
- A PR comment and GitHub Workflow [summary](https://github.com/gradle/develocity-actions?tab=readme-ov-file#summary) to ease navigation to the Build Scans
- Develocity [short-lived tokens](https://docs.gradle.com/develocity/api-manual/#short_lived_access_tokens) for authentication
- Build Scan publication only for build-reusable's `Build` step
- A rename from `GE_ACCESS_TOKEN` to `DV_ACCESS_TOKEN`

Note:
A new input `develocity-enabled` is added instead of relying on the presence of the token to enable the Build Scan publication behavior. This allows to publish Build Scans when secrets are not available, following [this approach](https://github.com/gradle/develocity-actions?tab=readme-ov-file#publish-build-scans-for-pull-requests-issued-from-forked-repositories).

Here is the summary that would be generated on the Log4j2's `build` workflow:
![Screenshot 2024-07-17 at 3 41 44 PM](https://github.com/user-attachments/assets/36021989-7e0c-432b-8fbc-b2b105765539)

2024-07-18 09:05 UTC, ppkarwasz requested changes
Thanks for this PR.
I tested it in [my private repo](https://github.com/ppkarwasz/logging-log4j2/actions/runs/9988254423) at it correctly publishes job summaries.

The `develocity-actions/setup-java` sets the `MAVEN_OPTS` variable for the entire workflow (including building the website). Maybe we should reset it in the `Clean up Develocity` step?

@vy, WDYT?

2024-07-18 11:47 UTC, jprinet commented on .github/workflows/build-reusable.yaml
> +        uses: gradle/develocity-actions/maven-setup@v1
Sure, let me get [this PR](https://github.com/gradle/develocity-actions/pull/37) merged before updating the commit ID

2024-07-19 05:57 UTC, ppkarwasz commented on .github/workflows/build-reusable.yaml
> +        uses: gradle/develocity-actions/maven-setup@v1
Great, so let's wait for that PR and then I think we are good to merge this one.

2024-07-19 12:29 UTC, jprinet commented on .github/workflows/build-reusable.yaml
> +        uses: gradle/develocity-actions/maven-setup@v1
It got merged, and I updated the code to pin the action 👍

2024-07-19 12:32 UTC, jprinet commented
Just a heads up @ppkarwasz that this PR will also add a comment to each submitted PR with the Build Scan summary table.
I find it valuable but you may consider that a workflow summary is sufficient.
If this is the case we can disable the PR comment with:
`add-pr-comment: false`

2024-07-19 12:33 UTC, ppkarwasz approved these changes

2024-07-19 12:36 UTC, merged